# Markdown lint rules
# Keep strict defaults, relax a few noisy ones
default: true

# Maximum line length
MD013: false

# Allow inline HTML in Markdown; HTMLProofer will validate HTML
MD033: false

# First line should be a top-level heading (not required for all docs)
MD041: false

